name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create kubeconfig
      run: |
        mkdir ${HOME}/.kube
    - name: Copy kubeconfig
      run: export KUBECONFIG=${{ secrets.KUBE_CONFIG }}
    - name: Get PO
      run: kubectl get po -A  
